name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      name: proton-${{ github.ref_name }}

  release:
    name: Release ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download ${{ github.ref_name }}.tar.xz artifact
      uses: actions/download-artifact@v4
      with:
        name: proton-${{ github.ref_name }}.tar.xz

    - name: Download ${{ github.ref_name }}.sha512sum artifact
      uses: actions/download-artifact@v4
      with:
        name: proton-${{ github.ref_name }}.sha512sum

    - name: Upload ${{ github.ref_name }}.tar.xz to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: proton-${{ github.ref_name }}.tar.xz
        overwrite: false

    - name: Upload ${{ github.ref_name }}.sha512sum to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        file: proton-${{ github.ref_name }}.sha512sum
        overwrite: false
